### PR TITLE
Reduce profile expiry time

### PR DESCRIPTION
**Pull request by AndrewFerr**
For #476

### CODE REVIEW

**Comment by tulir** [comment]
Probably better to just wait an hour for avatars to update 🤔

**Comment by AndrewFerr** [comment]
A compromise could be to add a bridge config option to set the profile expiry time.

The situation I wanted to avoid is someone changing their Signal avatar a few times & a Matrix user being unaware of it until later.

**Comment by tulir** [comment]
Yeah making it configurable is probably fine

**Comment by AndrewFerr** [comment]
Actually, a better way is to fetch the profile when receiving a `SyncMessage` with a `FetchLatest` indicating a profile change.  Then the existing fetch can remain as-is, but used as a safety check in case an on-demand was missed.

**Comment by AndrewFerr** [comment]
Pushed the config change for posterity, but abandoning this in favour of #482

**Comment by AndrewFerr** [comment]
It's been pointed out that the `SyncMessage` for profile changes is only for logged-in users, so it's not a full solution as I had thought.

Still, I'll leave this PR closed because reducing the profile expiry time incurs the risk of doing a lot of extra fetches, as it would trigger a fetch on _any_ new Signal message (plus some other Signal events) that happen after the expiry time, even if the profile hasn't changed.

**Pull request closed without merging**
